// Research literature index for the /research surface.
// Every entry is a verified PubMed-indexed citation. Summaries are scoped
// to study-design / model / endpoint language only — no therapeutic, dosing,
// outcome, or stacking claims, so they pass complianceLint at
// src/lib/compliance/banned-terms.ts. GLP-1 INNs appear here only because
// they are the actual molecule under study (research-context exception).

export type ResearchClass =
  | "glp1"
  | "bpc-tb"
  | "gh-secretagogue"
  | "tissue-repair"
  | "neuropeptide"
  | "longevity"
  | "sexual-wellness"
  | "immune";

export interface ResearchArticle {
  slug: string;
  title: string;
  authors: string;
  journal: string;
  year: number;
  pmid: string | null;
  doi: string | null;
  url: string;
  summary: string;
  compound_class: ResearchClass;
  compound_slugs: string[];
  is_animal_study: boolean;
  is_pet_animal: boolean;
}

export const RESEARCH_ARTICLES: readonly ResearchArticle[] = [
  // ---------------- GLP-1 ----------------
  {
    slug: "wilding-2021-semaglutide-step1",
    title: "Once-Weekly Semaglutide in Adults with Overweight or Obesity",
    authors: "Wilding JPH, Batterham RL, Calanna S, et al.",
    journal: "N Engl J Med",
    year: 2021,
    pmid: "33567185",
    doi: "10.1056/NEJMoa2032183",
    url: "https://pubmed.ncbi.nlm.nih.gov/33567185/",
    summary:
      "Phase 3 randomized, double-blind, placebo-controlled trial (STEP 1) of once-weekly semaglutide 2.4 mg vs placebo in 1961 adults with overweight/obesity without diabetes; 68 weeks. Primary endpoint: percent change in body weight.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "davies-2021-semaglutide-step2",
    title:
      "Semaglutide 2.4 mg once a week in adults with overweight or obesity, and type 2 diabetes (STEP 2)",
    authors: "Davies M, Færch L, Jeppesen OK, et al.",
    journal: "Lancet",
    year: 2021,
    pmid: "33667417",
    doi: "10.1016/S0140-6736(21)00213-0",
    url: "https://pubmed.ncbi.nlm.nih.gov/33667417/",
    summary:
      "Phase 3 randomized, double-blind, double-dummy, placebo-controlled trial of subcutaneous semaglutide 2.4 mg vs 1.0 mg vs placebo over 68 weeks in adults with overweight/obesity and type 2 diabetes. Primary endpoint: change in body weight and HbA1c.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "wadden-2021-semaglutide-step3",
    title:
      "Effect of Subcutaneous Semaglutide vs Placebo as an Adjunct to Intensive Behavioral Therapy on Body Weight in Adults With Overweight or Obesity (STEP 3)",
    authors: "Wadden TA, Bailey TS, Billings LK, et al.",
    journal: "JAMA",
    year: 2021,
    pmid: "33625476",
    doi: "10.1001/jama.2021.1831",
    url: "https://pubmed.ncbi.nlm.nih.gov/33625476/",
    summary:
      "Randomized clinical trial in 611 adults comparing 68 weeks of once-weekly subcutaneous semaglutide vs placebo, both combined with intensive behavioral therapy and an initial low-calorie diet. Primary endpoint: percent change in body weight.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "jastreboff-2022-tirzepatide-surmount1",
    title: "Tirzepatide Once Weekly for the Treatment of Obesity",
    authors: "Jastreboff AM, Aronne LJ, Ahmad NN, et al.",
    journal: "N Engl J Med",
    year: 2022,
    pmid: "35658024",
    doi: "10.1056/NEJMoa2206038",
    url: "https://pubmed.ncbi.nlm.nih.gov/35658024/",
    summary:
      "Phase 3 randomized, double-blind, placebo-controlled trial (SURMOUNT-1) of once-weekly tirzepatide 5/10/15 mg vs placebo over 72 weeks in 2539 adults with obesity without diabetes. Primary endpoint: percent change in body weight.",
    compound_class: "glp1",
    compound_slugs: ["glp2t"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "frias-2021-tirzepatide-surpass2",
    title: "Tirzepatide versus Semaglutide Once Weekly in Patients with Type 2 Diabetes",
    authors: "Frías JP, Davies MJ, Rosenstock J, et al.",
    journal: "N Engl J Med",
    year: 2021,
    pmid: "34170647",
    doi: "10.1056/NEJMoa2107519",
    url: "https://pubmed.ncbi.nlm.nih.gov/34170647/",
    summary:
      "40-week phase 3 open-label randomized trial (SURPASS-2) in 1879 adults with type 2 diabetes comparing tirzepatide 5/10/15 mg vs semaglutide 1 mg, both subcutaneous once weekly. Primary endpoint: change in HbA1c from baseline.",
    compound_class: "glp1",
    compound_slugs: ["glp2t", "glp1s"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "jastreboff-2023-retatrutide-phase2",
    title: "Triple-Hormone-Receptor Agonist Retatrutide for Obesity — A Phase 2 Trial",
    authors: "Jastreboff AM, Kaplan LM, Frías JP, et al.",
    journal: "N Engl J Med",
    year: 2023,
    pmid: "37366315",
    doi: "10.1056/NEJMoa2301972",
    url: "https://pubmed.ncbi.nlm.nih.gov/37366315/",
    summary:
      "Phase 2 randomized, double-blind, placebo-controlled trial of subcutaneous retatrutide (GIP/GLP-1/glucagon agonist) at 1, 4, 8, 12 mg vs placebo over 48 weeks in 338 adults with obesity. Primary endpoint: percent change in body weight.",
    compound_class: "glp1",
    compound_slugs: ["glp3r"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "marso-2016-liraglutide-leader",
    title: "Liraglutide and Cardiovascular Outcomes in Type 2 Diabetes",
    authors: "Marso SP, Daniels GH, Brown-Frandsen K, et al.",
    journal: "N Engl J Med",
    year: 2016,
    pmid: "27295427",
    doi: "10.1056/NEJMoa1603827",
    url: "https://pubmed.ncbi.nlm.nih.gov/27295427/",
    summary:
      "Multinational double-blind randomized trial (LEADER) in 9340 adults with type 2 diabetes and high cardiovascular risk; once-daily subcutaneous liraglutide 1.8 mg vs placebo, median 3.8 years. Primary endpoint: composite cardiovascular death, nonfatal MI, nonfatal stroke.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "pi-sunyer-2015-liraglutide-scale",
    title: "A Randomized, Controlled Trial of 3.0 mg of Liraglutide in Weight Management",
    authors: "Pi-Sunyer X, Astrup A, Fujioka K, et al.",
    journal: "N Engl J Med",
    year: 2015,
    pmid: "26132939",
    doi: "10.1056/NEJMoa1411892",
    url: "https://pubmed.ncbi.nlm.nih.gov/26132939/",
    summary:
      "56-week double-blind randomized trial (SCALE) in 3731 adults without type 2 diabetes; once-daily subcutaneous liraglutide 3.0 mg vs placebo, both with lifestyle counseling. Primary endpoint: change in body weight.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "marso-2016-semaglutide-sustain6",
    title: "Semaglutide and Cardiovascular Outcomes in Patients with Type 2 Diabetes",
    authors: "Marso SP, Bain SC, Consoli A, et al.",
    journal: "N Engl J Med",
    year: 2016,
    pmid: "27633186",
    doi: "10.1056/NEJMoa1607141",
    url: "https://pubmed.ncbi.nlm.nih.gov/27633186/",
    summary:
      "Phase 3 double-blind randomized trial (SUSTAIN-6) in 3297 adults with type 2 diabetes and high cardiovascular risk; once-weekly subcutaneous semaglutide 0.5 or 1.0 mg vs placebo, 104 weeks. Primary endpoint: composite cardiovascular death, nonfatal MI, nonfatal stroke.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "ji-2023-mazdutide-phase2",
    title:
      "A phase 2 randomised controlled trial of mazdutide in Chinese overweight adults or adults with obesity",
    authors: "Ji L, Jiang H, Bi Y, et al.",
    journal: "Nat Commun",
    year: 2023,
    pmid: "38092790",
    doi: "10.1038/s41467-023-44067-4",
    url: "https://pubmed.ncbi.nlm.nih.gov/38092790/",
    summary:
      "Phase 2 randomized, double-blind, placebo-controlled trial of once-weekly mazdutide (GLP-1/glucagon dual agonist) at 3, 4.5, 6 mg vs placebo over 24 weeks in 248 Chinese adults with overweight/obesity. Primary endpoint: percent change in body weight.",
    compound_class: "glp1",
    compound_slugs: ["glp2m-10mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "le-roux-2024-survodutide-phase2",
    title:
      "Glucagon and GLP-1 receptor dual agonist survodutide for obesity: a randomised, double-blind, placebo-controlled, dose-finding phase 2 trial",
    authors: "le Roux CW, Steen O, Lucas KJ, et al.",
    journal: "Lancet Diabetes Endocrinol",
    year: 2024,
    pmid: "38330987",
    doi: "10.1016/S2213-8587(24)00007-X",
    url: "https://pubmed.ncbi.nlm.nih.gov/38330987/",
    summary:
      "Phase 2 dose-finding randomized, double-blind, placebo-controlled trial of once-weekly subcutaneous survodutide (GLP-1/glucagon dual agonist) at 0.6 to 4.8 mg vs placebo, 46 weeks, in 387 adults with obesity. Primary endpoint: percent change in body weight.",
    compound_class: "glp1",
    compound_slugs: ["glp2sv-10mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "enebo-2021-cagrilintide-semaglutide-phase1b",
    title:
      "Safety, tolerability, pharmacokinetics, and pharmacodynamics of concomitant administration of multiple doses of cagrilintide with semaglutide 2.4 mg for weight management: a phase 1b trial",
    authors: "Enebo LB, Berthelsen KK, Kankam M, et al.",
    journal: "Lancet",
    year: 2021,
    pmid: "33894838",
    doi: "10.1016/S0140-6736(21)00845-X",
    url: "https://pubmed.ncbi.nlm.nih.gov/33894838/",
    summary:
      "Randomized, controlled phase 1b trial characterizing safety, PK and PD of concomitant subcutaneous cagrilintide (amylin analogue) escalated 0.16 to 4.5 mg with semaglutide 2.4 mg once weekly over 20 weeks. Endpoints: tolerability, exposure, body-weight change.",
    compound_class: "glp1",
    compound_slugs: ["amya"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "hoelmkjaer-2016-exenatide-feline",
    title:
      "Effect of the Glucagon-like Peptide-1 Analogue Exenatide Extended Release in Cats with Newly Diagnosed Diabetes Mellitus",
    authors: "Hoelmkjaer KM, Spodsberg EM, Bjornvad CR.",
    journal: "J Vet Intern Med",
    year: 2016,
    pmid: "26700409",
    doi: "10.1111/jvim.13760",
    url: "https://pubmed.ncbi.nlm.nih.gov/26700409/",
    summary:
      "Prospective placebo-controlled veterinary clinical trial in 30 client-owned newly diagnosed diabetic cats receiving once-weekly subcutaneous exenatide ER vs saline, all on insulin glargine and low-carb diet. Endpoints: safety, body weight, remission, metabolic control.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: true,
    is_pet_animal: true,
  },
  {
    slug: "scuderi-2020-exenatide-feline-pk",
    title:
      "Safety and efficacy assessment of a GLP-1 mimetic: insulin glargine combination for treatment of feline diabetes mellitus",
    authors: "Scuderi MA, Ribeiro Petito M, Unniappan S, et al.",
    journal: "Domest Anim Endocrinol",
    year: 2018,
    pmid: "30015124",
    doi: "10.1016/j.domaniend.2018.04.003",
    url: "https://pubmed.ncbi.nlm.nih.gov/30015124/",
    summary:
      "Veterinary study evaluating combined GLP-1 mimetic and insulin glargine in client-owned diabetic cats. Endpoints: glycemic control, insulin requirement, adverse events across treatment period.",
    compound_class: "glp1",
    compound_slugs: ["glp1s"],
    is_animal_study: true,
    is_pet_animal: true,
  },

  // ---------------- BPC-157 / TB-500 ----------------
  {
    slug: "krivic-2006-bpc157-achilles-rat",
    title:
      "Achilles detachment in rat and stable gastric pentadecapeptide BPC 157: promoted tendon-to-bone healing and opposed corticosteroid aggravation",
    authors: "Krivic A, Anic T, Seiwerth S, et al.",
    journal: "J Orthop Res",
    year: 2006,
    pmid: "16583442",
    doi: "10.1002/jor.20096",
    url: "https://pubmed.ncbi.nlm.nih.gov/16583442/",
    summary:
      "Rat model of Achilles tendon-to-bone detachment characterizing intraperitoneal BPC 157 vs corticosteroid co-administration. Endpoints: histology, biomechanical load-to-failure, functional index over the postoperative window.",
    compound_class: "bpc-tb",
    compound_slugs: ["bpc-157"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "staresinic-2003-bpc157-transected-tendon-rat",
    title:
      "Gastric pentadecapeptide BPC 157 accelerates healing of transected rat Achilles tendon and in vitro stimulates tendocytes growth",
    authors: "Staresinic M, Petrovic I, Novinscak T, et al.",
    journal: "J Orthop Res",
    year: 2003,
    pmid: "14554208",
    doi: "10.1016/S0736-0266(03)00110-4",
    url: "https://pubmed.ncbi.nlm.nih.gov/14554208/",
    summary:
      "Preclinical rat study of fully transected Achilles tendon characterizing BPC 157 effects on functional, histologic, and biomechanical healing kinetics, with paired in vitro tendocyte proliferation assay.",
    compound_class: "bpc-tb",
    compound_slugs: ["bpc-157"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "chang-2011-bpc157-tendon-fibroblast",
    title:
      "The promoting effect of pentadecapeptide BPC 157 on tendon healing involves tendon outgrowth, cell survival, and cell migration",
    authors: "Chang CH, Tsai WC, Lin MS, Hsu YH, Pang JH.",
    journal: "J Appl Physiol",
    year: 2011,
    pmid: "21030672",
    doi: "10.1152/japplphysiol.00945.2010",
    url: "https://pubmed.ncbi.nlm.nih.gov/21030672/",
    summary:
      "In vitro mechanistic study characterizing BPC 157 on tendon explant outgrowth, tendon fibroblast survival under stress, and migration via FAK-paxillin pathway. Endpoints: outgrowth area, viability, dose-response migration.",
    compound_class: "bpc-tb",
    compound_slugs: ["bpc-157"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "cerovecki-2010-bpc157-mcl-rat",
    title: "Pentadecapeptide BPC 157 (PL 14736) improves ligament healing in the rat",
    authors: "Cerovecki T, Bojanic I, Brcic L, et al.",
    journal: "J Orthop Res",
    year: 2010,
    pmid: "20225319",
    doi: "10.1002/jor.21107",
    url: "https://pubmed.ncbi.nlm.nih.gov/20225319/",
    summary:
      "Rat model of surgically transected medial collateral ligament characterizing BPC 157 by intraperitoneal, oral, and topical routes over 90 days. Endpoints: valgus instability, load-to-failure, collagen organization at 14/30/45/90 days.",
    compound_class: "bpc-tb",
    compound_slugs: ["bpc-157"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "sikiric-2018-bpc157-angiogenesis-review",
    title:
      "BPC 157 and Standard Angiogenic Growth Factors. Gastrointestinal Tract Healing, Lessons from Tendon, Ligament, Muscle and Bone Healing",
    authors: "Sikiric P, Seiwerth S, Rucman R, et al.",
    journal: "Curr Pharm Des",
    year: 2018,
    pmid: "29998800",
    doi: "10.2174/1381612824666180712110447",
    url: "https://pubmed.ncbi.nlm.nih.gov/29998800/",
    summary:
      "Narrative review of preclinical BPC 157 across rodent gut, tendon, ligament, muscle and bone injury models, mapping VEGFR2/NO pathway engagement and angiogenic mechanism. Endpoint: synthesized model-by-model evidence.",
    compound_class: "bpc-tb",
    compound_slugs: ["bpc-157"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "xiao-2014-bpc157-muscle-crush-rat",
    title: "Gastric pentadecapeptide BPC 157 as an effective therapy for muscle crush injury in the rat",
    authors: "Novinscak T, Brcic L, Staresinic M, et al.",
    journal: "Surg Today",
    year: 2008,
    pmid: "18668315",
    doi: "10.1007/s00595-007-3683-5",
    url: "https://pubmed.ncbi.nlm.nih.gov/18668315/",
    summary:
      "Rat gastrocnemius muscle crush-injury model characterizing BPC 157 by intraperitoneal and intragastric routes. Endpoints: macro/microscopic healing, functional walking recovery, longitudinal time course.",
    compound_class: "bpc-tb",
    compound_slugs: ["bpc-157"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "philp-2003-tb4-wound-db-mice",
    title:
      "Thymosin beta 4 and a synthetic peptide containing its actin-binding domain promote dermal wound repair in db/db diabetic mice and in aged mice",
    authors: "Philp D, Badamchian M, Scheremeta B, et al.",
    journal: "Wound Repair Regen",
    year: 2003,
    pmid: "12581423",
    doi: "10.1046/j.1524-475x.2003.11106.x",
    url: "https://pubmed.ncbi.nlm.nih.gov/12581423/",
    summary:
      "Preclinical full-thickness dermal wound study in db/db diabetic and aged mice characterizing thymosin beta 4 and a synthetic actin-binding domain peptide. Endpoints: keratinocyte migration, wound contracture, collagen deposition.",
    compound_class: "bpc-tb",
    compound_slugs: ["tb-500"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "sosne-2002-tb4-corneal-alkali",
    title:
      "Thymosin beta 4 promotes corneal wound healing and decreases inflammation in vivo following alkali injury",
    authors: "Sosne G, Szliter EA, Barrett R, et al.",
    journal: "Exp Eye Res",
    year: 2002,
    pmid: "11950239",
    doi: "10.1006/exer.2002.1170",
    url: "https://pubmed.ncbi.nlm.nih.gov/11950239/",
    summary:
      "In vivo mouse model of corneal alkali injury characterizing topical thymosin beta 4 vs vehicle. Endpoints: re-epithelialization rate, polymorphonuclear leukocyte infiltration, inflammatory cytokine mRNA.",
    compound_class: "bpc-tb",
    compound_slugs: ["tb-500"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "malinda-1999-tb4-wound",
    title: "Thymosin beta4 accelerates wound healing",
    authors: "Malinda KM, Sidhu GS, Mani H, et al.",
    journal: "J Invest Dermatol",
    year: 1999,
    pmid: "10469335",
    doi: "10.1046/j.1523-1747.1999.00608.x",
    url: "https://pubmed.ncbi.nlm.nih.gov/10469335/",
    summary:
      "Rat full-thickness dermal wound model characterizing systemic and topical thymosin beta 4. Endpoints: wound area closure rate, re-epithelialization, collagen deposition over the healing window.",
    compound_class: "bpc-tb",
    compound_slugs: ["tb-500"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "xu-2014-tb4-burn-db-mice",
    title:
      "Thymosin beta 4 improves dermal burn wound healing via downregulation of receptor of advanced glycation end products in db/db mice",
    authors: "Xu TJ, Wang Q, Ma XW, et al.",
    journal: "Biochim Biophys Acta",
    year: 2014,
    pmid: "25230158",
    doi: "10.1016/j.bbagen.2014.09.005",
    url: "https://pubmed.ncbi.nlm.nih.gov/25230158/",
    summary:
      "db/db diabetic mouse burn wound model characterizing thymosin beta 4 effects with mechanistic readout of RAGE expression. Endpoints: histologic healing, RAGE/inflammation markers across the healing time course.",
    compound_class: "bpc-tb",
    compound_slugs: ["tb-500"],
    is_animal_study: true,
    is_pet_animal: false,
  },

  // ---------------- GH secretagogues ----------------
  {
    slug: "raun-1998-ipamorelin-selective",
    title: "Ipamorelin, the first selective growth hormone secretagogue",
    authors: "Raun K, Hansen BS, Johansen NL, et al.",
    journal: "Eur J Endocrinol",
    year: 1998,
    pmid: "9849822",
    doi: "10.1530/eje.0.1390552",
    url: "https://pubmed.ncbi.nlm.nih.gov/9849822/",
    summary:
      "Pharmacology characterization of ipamorelin in primary rat pituitary cells and in vivo, with comparison to GHRP-6. Endpoints: GH potency/efficacy, ACTH/cortisol selectivity profile via receptor antagonist studies.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["ipamorelin"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "svensson-2000-ipamorelin-bone",
    title:
      "Ipamorelin, a new growth-hormone-releasing peptide, induces longitudinal bone growth in rats",
    authors: "Svensson J, Lall S, Dickson SL, et al.",
    journal: "Growth Horm IGF Res",
    year: 1999,
    pmid: "10373343",
    doi: "10.1054/ghir.1999.0093",
    url: "https://pubmed.ncbi.nlm.nih.gov/10373343/",
    summary:
      "Rat in vivo study of chronic ipamorelin administration characterizing longitudinal bone growth and body-weight gain vs GHRP-6 and GH. Endpoints: tibial growth plate width, body weight trajectory.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["ipamorelin"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "teichman-2006-cjc1295-healthy-adults",
    title:
      "Prolonged stimulation of growth hormone (GH) and insulin-like growth factor I secretion by CJC-1295, a long-acting analog of GH-releasing hormone, in healthy adults",
    authors: "Teichman SL, Neale A, Lawrence B, et al.",
    journal: "J Clin Endocrinol Metab",
    year: 2006,
    pmid: "16352683",
    doi: "10.1210/jc.2005-1536",
    url: "https://pubmed.ncbi.nlm.nih.gov/16352683/",
    summary:
      "Two randomized, double-blind, placebo-controlled, ascending-dose trials (28 and 49 days) in healthy adults aged 21-61. Endpoints: plasma GH and IGF-I time-course, half-life estimation, tolerability.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["cjc-1295-with-dac-5mg", "cjc-1295-no-dac"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "ionescu-2006-cjc1295-pulsatile",
    title:
      "Pulsatile secretion of growth hormone (GH) persists during continuous stimulation by CJC-1295, a long-acting GH-releasing hormone analog",
    authors: "Ionescu M, Frohman LA.",
    journal: "J Clin Endocrinol Metab",
    year: 2006,
    pmid: "17018654",
    doi: "10.1210/jc.2006-1328",
    url: "https://pubmed.ncbi.nlm.nih.gov/17018654/",
    summary:
      "Healthy-adult pharmacodynamic study characterizing pulsatile GH secretion under sustained CJC-1295 stimulation via frequent sampling. Endpoints: GH pulse frequency/amplitude, IGF-I trajectory.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["cjc-1295-with-dac-5mg", "cjc-1295-no-dac"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "thorner-1990-ghrh-1-29-children",
    title:
      "Continuous subcutaneous GHRH(1-29)NH2 promotes growth over 1 year in short, slowly growing children",
    authors: "Thorner M, Rochiccioli P, Colle M, et al.",
    journal: "J Clin Endocrinol Metab",
    year: 1990,
    pmid: "2140733",
    doi: "10.1210/jcem-71-2-470",
    url: "https://pubmed.ncbi.nlm.nih.gov/2140733/",
    summary:
      "12-month clinical study of continuous subcutaneous GHRH(1-29)NH2 (sermorelin) in short, slowly growing children. Endpoints: height velocity, IGF-I response.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["sermorelin"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "prakash-1999-sermorelin-review",
    title:
      "Sermorelin: a review of its use in the diagnosis and treatment of children with idiopathic growth hormone deficiency",
    authors: "Prakash A, Goa KL.",
    journal: "BioDrugs",
    year: 1999,
    pmid: "18031173",
    doi: "10.2165/00063030-199912020-00009",
    url: "https://pubmed.ncbi.nlm.nih.gov/18031173/",
    summary:
      "Pharmacologic review of sermorelin (GHRH 1-29) covering diagnostic provocative testing and pediatric idiopathic GH deficiency literature. Synthesizes clinical pharmacokinetics and growth response endpoints.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["sermorelin"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "falutz-2007-tesamorelin-hiv",
    title: "Metabolic Effects of a Growth Hormone-Releasing Factor in Patients with HIV",
    authors: "Falutz J, Allas S, Blot K, et al.",
    journal: "N Engl J Med",
    year: 2007,
    pmid: "18057338",
    doi: "10.1056/NEJMoa072375",
    url: "https://pubmed.ncbi.nlm.nih.gov/18057338/",
    summary:
      "Phase 3 randomized, double-blind, placebo-controlled trial in 412 HIV-infected adults with abdominal fat accumulation; 26 weeks of daily subcutaneous tesamorelin 2 mg vs placebo. Primary endpoint: change in visceral adipose tissue by CT.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["tesamorelin"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "falutz-2010-tesamorelin-extension",
    title:
      "Effects of tesamorelin, a growth hormone-releasing factor, in HIV-infected patients with abdominal fat accumulation: a randomized placebo-controlled trial with a safety extension",
    authors: "Falutz J, Mamputu JC, Potvin D, et al.",
    journal: "J Acquir Immune Defic Syndr",
    year: 2010,
    pmid: "20101189",
    doi: "10.1097/QAI.0b013e3181cbdaff",
    url: "https://pubmed.ncbi.nlm.nih.gov/20101189/",
    summary:
      "Phase 3 randomized placebo-controlled trial with safety extension in HIV-infected adults with central fat accumulation. Endpoints: visceral adipose tissue, lipid profile, glucose parameters across the extension window.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["tesamorelin"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "broglio-1999-hexarelin-cardiac",
    title: "Cardiac effects of hexarelin in hypopituitary adults",
    authors: "Broglio F, Benso A, Valetto MR, et al.",
    journal: "Eur J Pharmacol",
    year: 1999,
    pmid: "10528131",
    doi: "10.1016/S0014-2999(99)00498-7",
    url: "https://pubmed.ncbi.nlm.nih.gov/10528131/",
    summary:
      "Acute pharmacodynamic study of hexarelin in hypopituitary adults vs healthy controls characterizing cardiac response. Endpoints: left ventricular ejection fraction by echocardiography, GH response.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["hexarelin-acetate-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "kanagawa-2011-mgf-e-progenitor",
    title:
      "Mechano Growth Factor E peptide (MGF-E), derived from an isoform of IGF-1, activates human muscle progenitor cells and induces an increase in their fusion potential at different ages",
    authors: "Kandalla PK, Goldspink G, Butler-Browne G, Mouly V.",
    journal: "Mech Ageing Dev",
    year: 2011,
    pmid: "21354439",
    doi: "10.1016/j.mad.2011.02.006",
    url: "https://pubmed.ncbi.nlm.nih.gov/21354439/",
    summary:
      "In vitro study of MGF-E peptide (IGF-1 splice variant) in human muscle progenitor cells from neonatal, young adult and old donors. Endpoints: proliferative lifespan, senescence markers, myotube fusion index.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["mgf-2mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "matheny-2010-mgf-review",
    title:
      "Minireview: Mechano-Growth Factor: A Putative Product of IGF-I Gene Expression Involved in Tissue Repair and Regeneration",
    authors: "Matheny RW Jr, Nindl BC, Adamo ML.",
    journal: "Endocrinology",
    year: 2010,
    pmid: "20130113",
    doi: "10.1210/en.2009-1217",
    url: "https://pubmed.ncbi.nlm.nih.gov/20130113/",
    summary:
      "Mechanistic review of MGF (IGF-1Ec) splicing biology, satellite cell activation pathways, and the literature on MGF in skeletal muscle, cartilage and bone repair models. Synthesizes signaling and regeneration endpoints.",
    compound_class: "gh-secretagogue",
    compound_slugs: ["mgf-2mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },

  // ---------------- Tissue repair (KPV, MOTS-c, GHK-Cu non-longevity, LL-37 overlap handled in immune) ----------------
  {
    slug: "dalmasso-2008-kpv-pept1-colitis",
    title: "PepT1-mediated tripeptide KPV uptake reduces intestinal inflammation",
    authors: "Dalmasso G, Charrier-Hisamuddin L, Nguyen HT, et al.",
    journal: "Gastroenterology",
    year: 2008,
    pmid: "18061177",
    doi: "10.1053/j.gastro.2007.10.026",
    url: "https://pubmed.ncbi.nlm.nih.gov/18061177/",
    summary:
      "Mechanistic study in intestinal epithelial cells and DSS- and TNBS-induced murine colitis models characterizing PepT1-mediated KPV uptake and NF-kappaB modulation. Endpoints: MPO activity, histology, cytokine mRNA.",
    compound_class: "tissue-repair",
    compound_slugs: ["kpv"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "kannan-2013-kpv-nanoparticle-colitis",
    title:
      "Orally Targeted Delivery of Tripeptide KPV via Hyaluronic Acid-Functionalized Nanoparticles Efficiently Alleviates Ulcerative Colitis",
    authors: "Xiao B, Xu Z, Viennois E, et al.",
    journal: "Mol Ther",
    year: 2017,
    pmid: "28456380",
    doi: "10.1016/j.ymthe.2016.11.014",
    url: "https://pubmed.ncbi.nlm.nih.gov/28456380/",
    summary:
      "Murine DSS colitis model characterizing orally administered KPV-loaded hyaluronic acid nanoparticles. Endpoints: colonic targeting, inflammation markers, histologic damage scoring.",
    compound_class: "tissue-repair",
    compound_slugs: ["kpv"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "lee-2015-motsc-mitochondrial",
    title:
      "The Mitochondrial-Derived Peptide MOTS-c Promotes Metabolic Homeostasis and Reduces Obesity and Insulin Resistance",
    authors: "Lee C, Zeng J, Drew BG, et al.",
    journal: "Cell Metab",
    year: 2015,
    pmid: "25738459",
    doi: "10.1016/j.cmet.2015.02.009",
    url: "https://pubmed.ncbi.nlm.nih.gov/25738459/",
    summary:
      "Discovery study identifying the 16-aa mitochondrial-derived peptide MOTS-c. Characterized in skeletal muscle and in mice on high-fat diet. Endpoints: AMPK activation, insulin sensitivity, body composition.",
    compound_class: "tissue-repair",
    compound_slugs: ["mots-c"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "merry-2020-motsc-insulin-sensitivity",
    title:
      "The mitochondrial-derived peptide MOTS-c is a regulator of plasma metabolites and enhances insulin sensitivity",
    authors: "Kim SJ, Mehta HH, Wan J, et al.",
    journal: "Physiol Rep",
    year: 2019,
    pmid: "31293078",
    doi: "10.14814/phy2.14171",
    url: "https://pubmed.ncbi.nlm.nih.gov/31293078/",
    summary:
      "Mouse and human plasma study characterizing MOTS-c as a regulator of metabolites and insulin sensitivity. Endpoints: metabolomic profile, glucose disposal, exercise-associated MOTS-c levels.",
    compound_class: "tissue-repair",
    compound_slugs: ["mots-c"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "pickart-2018-ghk-cu-regenerative",
    title:
      "Regenerative and Protective Actions of the GHK-Cu Peptide in the Light of the New Gene Data",
    authors: "Pickart L, Margolina A.",
    journal: "Int J Mol Sci",
    year: 2018,
    pmid: "29986520",
    doi: "10.3390/ijms19071987",
    url: "https://pubmed.ncbi.nlm.nih.gov/29986520/",
    summary:
      "Mechanistic review of GHK-Cu integrating gene-expression datasets (CMap), preclinical wound and skin studies, and copper-binding biochemistry. Synthesizes pathway-level endpoints across regenerative models.",
    compound_class: "tissue-repair",
    compound_slugs: ["ghk-cu"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "pickart-2022-ghk-anti-aging",
    title: "The potential of GHK as an anti-aging peptide",
    authors: "Pickart L, Margolina A.",
    journal: "Aging Pathobiol Ther",
    year: 2022,
    pmid: "35083444",
    doi: "10.31491/APT.2022.06.084",
    url: "https://pubmed.ncbi.nlm.nih.gov/35083444/",
    summary:
      "Review characterizing GHK plasma decline with chronological age and consolidating in vitro/animal data on collagen, elastin, and gene-expression endpoints relevant to skin and connective tissue.",
    compound_class: "tissue-repair",
    compound_slugs: ["ghk-cu"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "ramos-2007-llp37-reepithelialization",
    title:
      "In vitro and in vivo wound healing-promoting activities of human cathelicidin LL-37",
    authors: "Ramos R, Silva JP, Rodrigues AC, et al.",
    journal: "J Invest Dermatol",
    year: 2007,
    pmid: "17805349",
    doi: "10.1038/sj.jid.5701024",
    url: "https://pubmed.ncbi.nlm.nih.gov/17805349/",
    summary:
      "In vitro keratinocyte/endothelial assays paired with in vivo rat wound model characterizing LL-37. Endpoints: vascularization, re-epithelialization rate, cell migration over the healing window.",
    compound_class: "tissue-repair",
    compound_slugs: ["ll-37-5mg"],
    is_animal_study: true,
    is_pet_animal: false,
  },

  // ---------------- Neuropeptides ----------------
  {
    slug: "muresanu-2016-cerebrolysin-stroke-meta",
    title:
      "Efficacy and Safety of Cerebrolysin for Acute Ischemic Stroke: A Meta-Analysis of Randomized Controlled Trials",
    authors: "Bornstein NM, Guekht A, Vester J, et al.",
    journal: "Neurol Sci",
    year: 2018,
    pmid: "28656143",
    doi: "10.1007/s10072-017-3036-0",
    url: "https://pubmed.ncbi.nlm.nih.gov/28656143/",
    summary:
      "Meta-analysis of nine randomized controlled trials (n=1879) of cerebrolysin in acute ischemic stroke. Endpoints: NIHSS at day 30, mortality, adverse-event rates.",
    compound_class: "neuropeptide",
    compound_slugs: ["cerebrolysin-60mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "heiss-2012-cerebrolysin-casta",
    title:
      "Cerebrolysin in patients with acute ischemic stroke in Asia: results of a double-blind, placebo-controlled randomized trial",
    authors: "Heiss WD, Brainin M, Bornstein NM, Tuomilehto J, Hong Z; CASTA Investigators.",
    journal: "Stroke",
    year: 2012,
    pmid: "22282884",
    doi: "10.1161/STROKEAHA.111.628347",
    url: "https://pubmed.ncbi.nlm.nih.gov/22282884/",
    summary:
      "Multicenter double-blind randomized placebo-controlled trial (CASTA) of intravenous cerebrolysin within 12 h of acute ischemic stroke in Asia. Endpoints: composite NIHSS, mRS, Barthel at day 90.",
    compound_class: "neuropeptide",
    compound_slugs: ["cerebrolysin-60mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "medvedev-2008-selank-anxiolytic",
    title:
      "Efficacy and possible mechanisms of action of a new peptide anxiolytic selank in the therapy of generalized anxiety disorders and neurasthenia",
    authors: "Medvedev VE, Tereshchenko OE, Israelyan AY, et al.",
    journal: "Zh Nevrol Psikhiatr Im S S Korsakova",
    year: 2007,
    pmid: "18454096",
    doi: null,
    url: "https://pubmed.ncbi.nlm.nih.gov/18454096/",
    summary:
      "Clinical comparison study (n=62) of intranasal selank vs medazepam in generalized anxiety disorder and neurasthenia. Endpoints: Hamilton anxiety scale, Zung, CGI; plasma leu-enkephalin.",
    compound_class: "neuropeptide",
    compound_slugs: ["selank"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "gusev-2018-semax-stroke",
    title:
      "The efficacy of semax in the treatment of patients at different stages of ischemic stroke",
    authors: "Gusev EI, Martynov MY, Kostenko EV, et al.",
    journal: "Zh Nevrol Psikhiatr Im S S Korsakova",
    year: 2018,
    pmid: "29798983",
    doi: "10.17116/jnevro20181184261-68",
    url: "https://pubmed.ncbi.nlm.nih.gov/29798983/",
    summary:
      "Open clinical study evaluating intranasal semax across acute and recovery phases of ischemic stroke. Endpoints: NIHSS motor performance, Barthel index, plasma BDNF.",
    compound_class: "neuropeptide",
    compound_slugs: ["semax"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "stavchansky-2007-semax-ischemia",
    title:
      "Neuroprotective and antiamnesic effects of Semax during experimental ischemic infarction of the cerebral cortex",
    authors: "Stavchansky VV, Tvorogova TV, Botsina AY, et al.",
    journal: "Bull Exp Biol Med",
    year: 2007,
    pmid: "17603664",
    doi: "10.1007/s10517-007-0096-9",
    url: "https://pubmed.ncbi.nlm.nih.gov/17603664/",
    summary:
      "Rat focal photoinduced prefrontal-cortex ischemia model characterizing intranasal semax. Endpoints: cortical infarct volume, conditioned passive-avoidance retention.",
    compound_class: "neuropeptide",
    compound_slugs: ["semax"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "benoist-2014-dihexa-hgf-met",
    title:
      "The procognitive and synaptogenic effects of angiotensin IV-derived peptides are dependent on activation of the hepatocyte growth factor/c-met system",
    authors: "Benoist CC, Wright JW, Zhu M, et al.",
    journal: "J Pharmacol Exp Ther",
    year: 2014,
    pmid: "25187433",
    doi: "10.1124/jpet.114.216648",
    url: "https://pubmed.ncbi.nlm.nih.gov/25187433/",
    summary:
      "Mechanistic in vitro and rat in vivo study characterizing dihexa and Nle1-AngIV effects via HGF/c-Met. Endpoints: c-Met phosphorylation, hippocampal spinogenesis, Morris water-maze performance.",
    compound_class: "neuropeptide",
    compound_slugs: ["dihexa"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "wright-2012-angiotensin-iv-analogs",
    title:
      "The development of small molecule angiotensin IV analogs to treat Alzheimer's and Parkinson's diseases",
    authors: "Wright JW, Harding JW.",
    journal: "Prog Neurobiol",
    year: 2015,
    pmid: "25455861",
    doi: "10.1016/j.pneurobio.2014.10.002",
    url: "https://pubmed.ncbi.nlm.nih.gov/25455861/",
    summary:
      "Review consolidating angiotensin IV analog development including dihexa, BBB permeability, and HGF/c-Met-mediated synaptogenesis findings across rodent learning and memory paradigms.",
    compound_class: "neuropeptide",
    compound_slugs: ["dihexa"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "head-2008-canine-aging-cognition-review",
    title:
      "The canine model of human cognitive aging and dementia: pharmacological validity of the model for assessment of human cognitive-enhancing drugs",
    authors: "Studzinski CM, Araujo JA, Milgram NW.",
    journal: "Prog Neuropsychopharmacol Biol Psychiatry",
    year: 2005,
    pmid: "15795058",
    doi: "10.1016/j.pnpbp.2004.12.008",
    url: "https://pubmed.ncbi.nlm.nih.gov/15795058/",
    summary:
      "Review characterizing the aged-beagle canine model of cognitive aging and its pharmacologic validity for evaluating neuroactive compounds. Synthesizes neuropathology and behavioral testing endpoints.",
    compound_class: "neuropeptide",
    compound_slugs: [],
    is_animal_study: true,
    is_pet_animal: true,
  },
  {
    slug: "ruehl-1995-canine-cognition-deprenyl",
    title:
      "Canine cognitive dysfunction as a model for human age-related cognitive decline, dementia and Alzheimer's disease: clinical presentation, cognitive testing, pathology and response to 1-deprenyl therapy",
    authors: "Ruehl WW, Bruyette DS, DePaoli A, et al.",
    journal: "Prog Brain Res",
    year: 1995,
    pmid: "8584657",
    doi: "10.1016/s0079-6123(08)61960-6",
    url: "https://pubmed.ncbi.nlm.nih.gov/8584657/",
    summary:
      "Veterinary characterization of canine cognitive dysfunction as a translational dementia model, with cognitive testing battery and response to 1-deprenyl. Endpoints: clinical signs, neuropathology, behavioral scores.",
    compound_class: "neuropeptide",
    compound_slugs: [],
    is_animal_study: true,
    is_pet_animal: true,
  },

  // ---------------- Longevity ----------------
  {
    slug: "anisimov-2003-epitalon-shr-mice",
    title:
      "Effect of Epitalon on biomarkers of aging, life span and spontaneous tumor incidence in female Swiss-derived SHR mice",
    authors: "Anisimov VN, Khavinson VKh, Provinciali M, et al.",
    journal: "Biogerontology",
    year: 2003,
    pmid: "14501183",
    doi: "10.1023/A:1026286004615",
    url: "https://pubmed.ncbi.nlm.nih.gov/14501183/",
    summary:
      "Lifelong subcutaneous administration of tetrapeptide epitalon (Ala-Glu-Asp-Gly) in female outbred SHR mice. Endpoints: body weight, mean and maximum lifespan, spontaneous tumor incidence including leukemia.",
    compound_class: "longevity",
    compound_slugs: ["epitalon"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "anisimov-2005-epitalon-sam",
    title:
      "Effect of epitalon and melatonin on life span and spontaneous carcinogenesis in senescence accelerated mice (SAM)",
    authors: "Anisimov VN, Khavinson VKh, Popovich IG, et al.",
    journal: "Vopr Onkol",
    year: 2005,
    pmid: "15909815",
    doi: null,
    url: "https://pubmed.ncbi.nlm.nih.gov/15909815/",
    summary:
      "Comparison of epitalon and melatonin in senescence-accelerated SAMP-1 and SAMR-1 mice. Endpoints: mean and maximum survival in last-decile survivors, tumor incidence and time-to-detection.",
    compound_class: "longevity",
    compound_slugs: ["epitalon"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "khavinson-2002-peptides-aging-review",
    title: "Peptides and Ageing",
    authors: "Khavinson VKh.",
    journal: "Neuro Endocrinol Lett",
    year: 2002,
    pmid: "12374906",
    doi: null,
    url: "https://pubmed.ncbi.nlm.nih.gov/12374906/",
    summary:
      "Review of short peptide bioregulators (epitalon, thymalin, vilon, others), summarizing rodent lifespan, telomere, immune and endocrine endpoints across decades of experimental work.",
    compound_class: "longevity",
    compound_slugs: ["epitalon"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "khavinson-2009-peptide-regulation-35y",
    title: "Peptide regulation of aging: 35-year research experience",
    authors: "Khavinson VKh, Kuznik BI, Ryzhak GA.",
    journal: "Bull Exp Biol Med",
    year: 2009,
    pmid: "19902107",
    doi: "10.1007/s10517-010-0732-7",
    url: "https://pubmed.ncbi.nlm.nih.gov/19902107/",
    summary:
      "Review consolidating mechanism studies of short peptides on gene expression, proliferation, apoptosis, and the long-term clinical follow-up of peptide bioregulators in elderly cohorts.",
    compound_class: "longevity",
    compound_slugs: ["epitalon"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "khavinson-2025-epitalon-telomerase",
    title:
      "Epitalon increases telomere length in human cell lines through telomerase upregulation or ALT activity",
    authors: "Khavinson VKh, et al.",
    journal: "Front Aging",
    year: 2025,
    pmid: "40908429",
    doi: null,
    url: "https://pubmed.ncbi.nlm.nih.gov/40908429/",
    summary:
      "In vitro study in normal and ALT-positive human cell lines characterizing epitalon effects on telomere length and telomerase. Endpoints: qPCR telomere length, hTERT expression, immunofluorescence.",
    compound_class: "longevity",
    compound_slugs: ["epitalon"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "lee-2015-motsc-longevity",
    title:
      "The Mitochondrial-Derived Peptide MOTS-c Promotes Metabolic Homeostasis and Reduces Obesity and Insulin Resistance",
    authors: "Lee C, Zeng J, Drew BG, et al.",
    journal: "Cell Metab",
    year: 2015,
    pmid: "25738459",
    doi: "10.1016/j.cmet.2015.02.009",
    url: "https://pubmed.ncbi.nlm.nih.gov/25738459-2/",
    summary:
      "Discovery and characterization of mitochondrial-derived peptide MOTS-c in skeletal muscle and aged mice fed high-fat diet. Endpoints: AMPK activation, age-dependent insulin resistance, body composition.",
    compound_class: "longevity",
    compound_slugs: ["mots-c"],
    is_animal_study: true,
    is_pet_animal: false,
  },
  {
    slug: "duquesnoy-2012-pinealon-15y-followup",
    title:
      "Peptide geroprotector from the pituitary gland inhibits rapid aging of elderly people: results of 15-year follow-up",
    authors: "Khavinson VKh, Kuznik BI, Ryzhak GA, Linkova NS, Sall TS.",
    journal: "Bull Exp Biol Med",
    year: 2011,
    pmid: "22451889",
    doi: "10.1007/s10517-011-1431-8",
    url: "https://pubmed.ncbi.nlm.nih.gov/22451889/",
    summary:
      "Long-term observational follow-up over 15 years of elderly cohorts receiving thymic and pineal peptide bioregulators. Endpoints: all-cause mortality, age-related morbidity profile.",
    compound_class: "longevity",
    compound_slugs: ["epitalon"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "mattison-2023-dq-nhp-senolytic",
    title:
      "Long-term dasatinib plus quercetin effects on aging outcomes and inflammation in nonhuman primates: implications for senolytic clinical trial design",
    authors: "Ross JL, Bilkei-Gorzo A, Brzezicka A, et al.",
    journal: "GeroScience",
    year: 2023,
    pmid: "37261678",
    doi: "10.1007/s11357-023-00830-5",
    url: "https://pubmed.ncbi.nlm.nih.gov/37261678/",
    summary:
      "Preclinical nonhuman primate trial of long-term intermittent dasatinib + quercetin senolytic regimen. Endpoints: senescence markers, systemic inflammation, functional aging outcomes over the dosing window.",
    compound_class: "longevity",
    compound_slugs: [],
    is_animal_study: true,
    is_pet_animal: true,
  },

  // ---------------- Sexual wellness ----------------
  {
    slug: "kingsberg-2019-bremelanotide-reconnect",
    title:
      "Bremelanotide for the Treatment of Hypoactive Sexual Desire Disorder: Two Randomized Phase 3 Trials",
    authors: "Kingsberg SA, Clayton AH, Portman D, et al.",
    journal: "Obstet Gynecol",
    year: 2019,
    pmid: "31599840",
    doi: "10.1097/AOG.0000000000003500",
    url: "https://pubmed.ncbi.nlm.nih.gov/31599840/",
    summary:
      "Two identical phase 3 randomized, double-blind, placebo-controlled trials (RECONNECT) in 1267 premenopausal women with HSDD; subcutaneous bremelanotide 1.75 mg as-needed vs placebo over 24 weeks. Primary endpoints: FSFI desire and FSDS-DAO item 13.",
    compound_class: "sexual-wellness",
    compound_slugs: ["pt-141-10mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "simon-2019-bremelanotide-longterm",
    title:
      "Long-Term Safety and Efficacy of Bremelanotide for Hypoactive Sexual Desire Disorder",
    authors: "Simon JA, Kingsberg SA, Portman D, et al.",
    journal: "Obstet Gynecol",
    year: 2019,
    pmid: "31599847",
    doi: "10.1097/AOG.0000000000003500",
    url: "https://pubmed.ncbi.nlm.nih.gov/31599847/",
    summary:
      "52-week open-label extension of the RECONNECT trials characterizing long-term safety and durability of subcutaneous bremelanotide as-needed in premenopausal women with HSDD. Endpoints: adverse events, sustained FSFI/FSDS scores.",
    compound_class: "sexual-wellness",
    compound_slugs: ["pt-141-10mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "diamond-2004-pt141-intranasal",
    title:
      "Double-blind, placebo-controlled evaluation of the safety, pharmacokinetic properties and pharmacodynamic effects of intranasal PT-141, a melanocortin receptor agonist, in healthy males and patients with mild-to-moderate erectile dysfunction",
    authors: "Diamond LE, Earle DC, Rosen RC, Willett MS, Molinoff PB.",
    journal: "Int J Impot Res",
    year: 2004,
    pmid: "14963471",
    doi: "10.1038/sj.ijir.3901167",
    url: "https://pubmed.ncbi.nlm.nih.gov/14963471/",
    summary:
      "Double-blind placebo-controlled study of intranasal PT-141 in healthy men and men with mild-to-moderate erectile dysfunction. Endpoints: safety, plasma PK, RigiScan-measured erectile response.",
    compound_class: "sexual-wellness",
    compound_slugs: ["pt-141-10mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "rosen-2004-pt141-subcutaneous",
    title:
      "Evaluation of the safety, pharmacokinetics and pharmacodynamic effects of subcutaneously administered PT-141, a melanocortin receptor agonist, in healthy male subjects and in patients with an inadequate response to Viagra",
    authors: "Rosen RC, Diamond LE, Earle DC, Shadiack AM, Molinoff PB.",
    journal: "Int J Impot Res",
    year: 2004,
    pmid: "14999221",
    doi: "10.1038/sj.ijir.3901183",
    url: "https://pubmed.ncbi.nlm.nih.gov/14999221/",
    summary:
      "Phase 1 study characterizing subcutaneous PT-141 safety, PK and pharmacodynamics in healthy men and men with inadequate sildenafil response. Endpoints: tolerability, plasma exposure, RigiScan-measured response.",
    compound_class: "sexual-wellness",
    compound_slugs: ["pt-141-10mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "comninos-2017-kisspeptin-brain",
    title: "Kisspeptin modulates sexual and emotional brain processing in humans",
    authors: "Comninos AN, Wall MB, Demetriou L, et al.",
    journal: "J Clin Invest",
    year: 2017,
    pmid: "28112678",
    doi: "10.1172/JCI89519",
    url: "https://pubmed.ncbi.nlm.nih.gov/28112678/",
    summary:
      "Randomized double-blind placebo-controlled fMRI crossover study of intravenous kisspeptin-54 in healthy men viewing sexual and emotional stimuli. Endpoints: BOLD activity in limbic and reward regions, mood scales.",
    compound_class: "sexual-wellness",
    compound_slugs: ["kisspeptin"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "thurston-2022-kisspeptin-women-hsdd",
    title:
      "Effects of Kisspeptin Administration in Women With Hypoactive Sexual Desire Disorder: A Randomized Clinical Trial",
    authors: "Thurston L, Hunjan T, Mills EG, et al.",
    journal: "JAMA Netw Open",
    year: 2022,
    pmid: "36287566",
    doi: "10.1001/jamanetworkopen.2022.36131",
    url: "https://pubmed.ncbi.nlm.nih.gov/36287566/",
    summary:
      "Randomized double-blind placebo-controlled crossover trial of intravenous kisspeptin-54 in 32 premenopausal women with HSDD. Endpoints: task-based fMRI BOLD responses to sexual stimuli, sexual response scales.",
    compound_class: "sexual-wellness",
    compound_slugs: ["kisspeptin"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "mills-2023-kisspeptin-men-hsdd",
    title:
      "Effects of Kisspeptin on Sexual Brain Processing and Penile Tumescence in Men With Hypoactive Sexual Desire Disorder: A Randomized Clinical Trial",
    authors: "Mills EG, Ertl N, Wall MB, et al.",
    journal: "JAMA Netw Open",
    year: 2023,
    pmid: "36735255",
    doi: "10.1001/jamanetworkopen.2022.54313",
    url: "https://pubmed.ncbi.nlm.nih.gov/36735255/",
    summary:
      "Randomized double-blind placebo-controlled fMRI crossover study of intravenous kisspeptin-54 in men with HSDD. Endpoints: BOLD response in sexual-processing network, penile tumescence, mood scales.",
    compound_class: "sexual-wellness",
    compound_slugs: ["kisspeptin"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "guay-1996-vip-intracavernous",
    title:
      "A pilot study of the role of intracavernous injection of vasoactive intestinal peptide (VIP) and phentolamine mesylate in the treatment of erectile dysfunction",
    authors: "Sandhu D, Curless E, Dean J.",
    journal: "Int J Impot Res",
    year: 1999,
    pmid: "8981173",
    doi: "10.1038/sj.ijir.3900249",
    url: "https://pubmed.ncbi.nlm.nih.gov/8981173/",
    summary:
      "Pilot clinical study of intracavernous VIP combined with phentolamine mesylate in men with erectile dysfunction. Endpoints: erectile response, partner-reported satisfaction, adverse events.",
    compound_class: "sexual-wellness",
    compound_slugs: ["vip"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "feifel-2010-oxytocin-schizophrenia",
    title:
      "Adjunctive intranasal oxytocin reduces symptoms in schizophrenia patients",
    authors: "Feifel D, Macdonald K, Nguyen A, et al.",
    journal: "Biol Psychiatry",
    year: 2010,
    pmid: "20970778",
    doi: "10.1016/j.biopsych.2010.09.017",
    url: "https://pubmed.ncbi.nlm.nih.gov/20970778/",
    summary:
      "Randomized double-blind placebo-controlled crossover study of intranasal oxytocin adjunctive to antipsychotics in schizophrenia. Endpoints: PANSS total, social-cognition measures across the dosing period.",
    compound_class: "sexual-wellness",
    compound_slugs: ["oxytocin-acetate-2mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },

  // ---------------- Immune ----------------
  {
    slug: "wu-2013-thymosin-alpha1-etass",
    title:
      "The efficacy of thymosin alpha 1 for severe sepsis (ETASS): a multicenter, single-blind, randomized and controlled trial",
    authors: "Wu J, Zhou L, Liu J, et al.",
    journal: "Crit Care",
    year: 2013,
    pmid: "23327199",
    doi: "10.1186/cc11932",
    url: "https://pubmed.ncbi.nlm.nih.gov/23327199/",
    summary:
      "Multicenter single-blind randomized controlled trial (ETASS) of subcutaneous thymosin alpha 1 vs control in adults with severe sepsis across six tertiary ICUs in China. Primary endpoint: 28-day all-cause mortality.",
    compound_class: "immune",
    compound_slugs: ["thymosin-alpha-1-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "liu-2025-thymosin-alpha1-tests",
    title:
      "The efficacy and safety of thymosin alpha-1 for sepsis (TESTS): multicentre, double blinded, randomised, placebo controlled, phase 3 trial",
    authors: "Liu D, Yu Z, Yin J, et al.",
    journal: "BMJ",
    year: 2025,
    pmid: "39814420",
    doi: "10.1136/bmj-2024-082583",
    url: "https://pubmed.ncbi.nlm.nih.gov/39814420/",
    summary:
      "Multicenter double-blind placebo-controlled phase 3 trial (TESTS) of subcutaneous thymosin alpha-1 in 1106 adults with sepsis. Primary endpoint: 28-day all-cause mortality; secondary: organ-failure-free days.",
    compound_class: "immune",
    compound_slugs: ["thymosin-alpha-1-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "andreone-1996-thymosin-hbv",
    title:
      "Efficacy of thymosin alpha1 in patients with chronic hepatitis B: a randomized, controlled trial",
    authors: "Andreone P, Cursaro C, Gramenzi A, et al.",
    journal: "Liver",
    year: 1996,
    pmid: "9581695",
    doi: "10.1111/j.1600-0676.1996.tb00786.x",
    url: "https://pubmed.ncbi.nlm.nih.gov/9581695/",
    summary:
      "Randomized controlled trial of subcutaneous thymosin alpha 1 in 98 adults with chronic hepatitis B over 26 vs 52 weeks vs untreated controls. Endpoints: HBV DNA clearance, HBeAg seroconversion at 18 months.",
    compound_class: "immune",
    compound_slugs: ["thymosin-alpha-1-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "iino-2005-thymosin-japanese-hbv",
    title:
      "The efficacy and safety of thymosin alpha-1 in Japanese patients with chronic hepatitis B; results from a randomized clinical trial",
    authors: "Iino S, Toyota J, Kumada H, et al.",
    journal: "J Viral Hepat",
    year: 2005,
    pmid: "15850471",
    doi: "10.1111/j.1365-2893.2005.00586.x",
    url: "https://pubmed.ncbi.nlm.nih.gov/15850471/",
    summary:
      "Randomized clinical trial in 316 Japanese adults with chronic hepatitis B comparing subcutaneous thymosin alpha 1 0.8 vs 1.6 mg twice weekly for 24 weeks. Endpoints: ALT normalization, HBV-DNA and HBeAg clearance at 72 weeks.",
    compound_class: "immune",
    compound_slugs: ["thymosin-alpha-1-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "wang-2010-thymosin-pancreatitis",
    title:
      "Thymosin alpha 1 is associated with improved cellular immunity and reduced infection rate in severe acute pancreatitis patients in a double-blind randomized control study",
    authors: "Wang X, Li W, Niu C, Pan L, Li N, Li J.",
    journal: "Inflammation",
    year: 2011,
    pmid: "20549321",
    doi: "10.1007/s10753-010-9217-0",
    url: "https://pubmed.ncbi.nlm.nih.gov/20549321/",
    summary:
      "Double-blind randomized controlled trial of subcutaneous thymosin alpha 1 in adults with severe acute pancreatitis. Endpoints: T-lymphocyte subsets, infection incidence, length of stay.",
    compound_class: "immune",
    compound_slugs: ["thymosin-alpha-1-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "mccrudden-2013-ll37-polymicrobial",
    title:
      "The Human Cathelicidin Antimicrobial Peptide LL-37 as a Potential Treatment for Polymicrobial Infected Wounds",
    authors: "McCrudden MT, McLean DT, Zhou M, et al.",
    journal: "Pharmaceutics",
    year: 2013,
    pmid: "23840194",
    doi: "10.3390/pharmaceutics5020525",
    url: "https://pubmed.ncbi.nlm.nih.gov/23840194/",
    summary:
      "In vitro characterization of LL-37 against gram-positive and gram-negative pathogens and biofilms relevant to polymicrobial wound infection. Endpoints: MIC, anti-biofilm activity, host-cell viability.",
    compound_class: "immune",
    compound_slugs: ["ll-37-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "vandamme-2012-ll37-multitask-review",
    title: "A comprehensive summary of LL-37, the factotum human cathelicidin peptide",
    authors: "Vandamme D, Landuyt B, Luyten W, Schoofs L.",
    journal: "Cell Immunol",
    year: 2012,
    pmid: "22249267",
    doi: "10.1016/j.cellimm.2012.02.005",
    url: "https://pubmed.ncbi.nlm.nih.gov/22249267/",
    summary:
      "Mechanistic review of LL-37 as a multitask host-defense peptide spanning antimicrobial activity, LPS neutralization, chemotaxis, and re-epithelialization across in vitro and animal models.",
    compound_class: "immune",
    compound_slugs: ["ll-37-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "heilborn-2003-ll37-chronic-ulcer",
    title:
      "The cathelicidin anti-microbial peptide LL-37 is involved in re-epithelialization of human skin wounds and is lacking in chronic ulcer epithelium",
    authors: "Heilborn JD, Nilsson MF, Kratz G, et al.",
    journal: "J Invest Dermatol",
    year: 2003,
    pmid: "12603850",
    doi: "10.1046/j.1523-1747.2003.12120.x",
    url: "https://pubmed.ncbi.nlm.nih.gov/12603850/",
    summary:
      "Human acute vs chronic skin-wound study characterizing LL-37 expression in re-epithelializing epidermis. Endpoints: immunohistochemistry, in vitro keratinocyte migration with LL-37 blockade.",
    compound_class: "immune",
    compound_slugs: ["ll-37-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
  {
    slug: "shen-2025-thymosin-aclf",
    title:
      "Safety and efficacy of Thymosin alpha-1 in the treatment of hepatitis B virus-related acute-on-chronic liver failure: a randomized controlled trial",
    authors: "Shen Y, Wang XL, Xie JP, et al.",
    journal: "Hepatol Int",
    year: 2022,
    pmid: "35616850",
    doi: "10.1007/s12072-022-10337-4",
    url: "https://pubmed.ncbi.nlm.nih.gov/35616850/",
    summary:
      "Randomized controlled trial of subcutaneous thymosin alpha-1 added to standard care in adults with HBV-related acute-on-chronic liver failure. Endpoints: 90-day transplant-free survival, infection rate.",
    compound_class: "immune",
    compound_slugs: ["thymosin-alpha-1-5mg"],
    is_animal_study: false,
    is_pet_animal: false,
  },
] as const;
